# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat_exchange', '0002_user_suspend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='file_path',
            field=models.FileField(upload_to='audio/'),
        ),
    ]
