# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beat_exchange', '0003_auto_20180627_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beat',
            old_name='user_id',
            new_name='user',
        ),
    ]
